### ISSUE TITLE
Make callback function optional in streaming request

### ISSUE THREAD

**Issue by marinac-dev** [marinac-dev/openai#1]
Currently, `stream()` function for POST requests has a required callback function that handles responses.
However, there are situations where users might need to handle responses themselves with custom implementation, and would prefer to omit the built-in callback function. 
Therefore, I would like to make the callback function as a parameter.

**Comment by wtedw** [comment]
Hey thanks for this library. I'm already using this and had a suggestion.
This is how I'm using it internally

  
```
def chat_completion(%{stream: true} = prompt, options, stream_callback \\ &stream_callback_accumulate/2) do
    jdata = Jason.encode!(prompt)
    conn = %{headers: nil, status: nil, body: [], type: :stream}
    stream(:post, "", jdata, options, conn, stream_callback )
  end
  
defp stream_callback_accumulate({:status, data}, acc), do: %{acc | status: data}
defp stream_callback_accumulate({:headers, headers}, acc), do: %{acc | headers: headers}
defp stream_callback_accumulate({:data, data}, %{body: body} = acc), do: %{acc | body: [data | body]}
```

I renamed the default stream_callback to stream_callback_accumulate because it was not immediately clear to me that it's using streams to accumulate all the data. 

This is just extra info for anybody looking at this. Later I use a GenServer in my Phoenix project to call the chat_completion function so that it can asynchronously perform the request and send a message back to my LiveView process of the stream tokens.

```
# GenServer
OpenAi.chat_completion(
    %{
      model: "gpt-3.5-turbo",
      messages: messages,
      stream: true
      # max_tokens: 1024,
      # High temperature leads to a more creative response.
      # temperature: 0.0
    },
    [],
    &handle_stream_data(liveview_pid, &1, &2)
  )
```

```
# LiveView 
def handle_call({:handle_stream_token, token}, _from, socket) do
  {:reply, :ok, stream_insert(socket, :tokens, token)}
end
```

Let me know if you want a PR for this

**Comment by marinac-dev** [comment]
Hi there! 
I had that idea in mind, you don't have to bother with PR, I already have it on my roadmap and will do it later today.

**Comment by wtedw** [comment]
Awesome, thanks!
